table Empresa
	lineageTag: 028cb692-589c-4572-b87b-b6ca8ae17976

	column 'ID Empresa'
		dataType: int64
		formatString: 0
		lineageTag: e84e681f-4711-4c24-a33b-6a28fc8b5c7a
		summarizeBy: none
		sourceColumn: ID Empresa

		annotation SummarizationSetBy = User

	column 'Razón Social'
		dataType: string
		lineageTag: e8a913ea-4c78-4330-bedb-e08c63c21110
		summarizeBy: none
		sourceColumn: Razón Social

		annotation SummarizationSetBy = Automatic

	column 'Nombre de Fantasía'
		dataType: string
		lineageTag: 5ddb08bc-1058-4ba1-bb47-19e4c089aaf4
		summarizeBy: none
		sourceColumn: Nombre de Fantasía

		annotation SummarizationSetBy = Automatic

	column Filial
		dataType: string
		lineageTag: d564f198-75d5-40be-a8c4-3869c8e4c022
		summarizeBy: none
		sourceColumn: Filial

		annotation SummarizationSetBy = Automatic

	partition Empresa = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Juan\Desktop\Asistencia al Viajero.xlsx"), null, true),
				    Empresa_Sheet = Origen{[Item="Empresa",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Empresa_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID Empresa", Int64.Type}, {"Razón Social", type text}, {"Nombre de Fantasía", type text}, {"Filial", type text}}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Filas en blanco eliminadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

