table Producto
	lineageTag: 9b449b2f-a541-4705-bdd7-c16c4c103190

	column 'ID Producto'
		dataType: int64
		formatString: 0
		lineageTag: 73fa5ae5-cf6a-418e-8a38-ca5baf4dc180
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = User

	column 'Nombre Producto'
		dataType: string
		lineageTag: 6841ab4a-7583-4c6b-ab2e-88bf05ba1912
		summarizeBy: none
		sourceColumn: Nombre Producto

		annotation SummarizationSetBy = Automatic

	partition Producto = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Juan\Desktop\Asistencia al Viajero.xlsx"), null, true),
				    Producto_Sheet = Origen{[Item="Producto",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Producto_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID Producto", Int64.Type}, {"Nombre Producto", type text}}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Filas en blanco eliminadas"

	annotation PBI_ResultType = Table

